The initial code commit with one working integration test.
openfoodfacts/openfoodfacts-csharp pull request #1
Opened 2023-10-26 01:41 UTC by MadInventorQDB

### What
The initial code commit with data models, client, and service.

### Screenshot
N/A

### Fixes bug(s)
N/A

### Part of 
N/A

2023-10-26 08:43 UTC, aberteau requested changes
Thank you so much for your work. 💪👏

I noted some corrections/remarks. Some are a personal point of view.
I am at your disposal if you wish to discuss it. 😉

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/Images.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/Ingredient.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Clients/OpenFoodFactsApiLowLevelClient.cs
> +namespace pl.coderion.client
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Clients)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/LanguagesCodes.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/NutrientLevels.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/Nutriments.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/ProductResponse.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/Nutriments.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/ProductResponse.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImage.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImageItem.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImages.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Models/Source.cs
> +namespace pl.coderion.model
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Models)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Services/OpenFoodFactsWrapperImpl.cs
> +namespace pl.coderion.service.impl
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Services)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
It could be interesting to target "netstandard2.0" or "netstandard2.1" so as not to restrict its use to the .net 6 (and above.) This allows its use on a larger number of platforms.

- netstandard2.0
https://learn.microsoft.com/en-US/dotnet/standard/net-standard?tabs=net-standard-2-0
.Net and .Net Core (2.0, 2.1, 2.2, 3.0, 3.1, 5.0, 6.0, 7.0), .Net framework (4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1), Xamarin, ...

- netstandard2.1
https://learn.microsoft.com/en-US/dotnet/standard/net-standard?tabs=net-standard-2-1
.Net and .Net Core (3.0, 3.1, 5.0, 6.0, 7.0), Xamarin, ...

I would tend to prefer "netstandard 2.0" which covers a larger number of platforms but I'll let you choose what seems most relevant to you. (net6.0, netstandard2.0 or netstandard2.1)

2023-10-26 08:43 UTC, aberteau commented on openfoodfacts-csharp/Services/Interfaces/IOpenFoodFactsWrapper.cs
> +namespace pl.coderion.service
Namespace doesn't correspond to file location / project organization. (For example : OpenFoodFactsCSharp.Services.Interfaces)

2023-10-26 08:48 UTC, hangy commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Could also use multi-targeting to target both, but in general netstandard2.0 is pretty good

2023-10-26 08:53 UTC, aberteau commented on openfoodfacts-csharp/Models/Product.cs
All properties are Camel Case. Can you please use Pascal Case ?

2023-10-26 09:29 UTC, hangy commented on openfoodfacts-csharp/Models/Product.cs
In general, it could be good to add a `.editorconfig` that helps use some standard code-style. I really like using tried variants like [the from the .NET runtime](https://github.com/dotnet/runtime/blob/7de4e1b1d9f102fdbf37c7bc41f47979829422a1/.editorconfig), for example.

2023-10-26 12:07 UTC, aberteau commented on openfoodfacts-csharp/Models/Product.cs
Thanks @hangy for this suggestion. 👍
I think you could submit a pull request for this.
All can always be improved. @MadInventorQDB has already done a lot of work.
This is an excellent base that we can gradually improve.
`.editorconfig` can be the next step. 😉

2023-10-26 22:48 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Images.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Ingredient.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Clients/OpenFoodFactsApiLowLevelClient.cs
> +namespace pl.coderion.client
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/LanguagesCodes.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/NutrientLevels.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/SelectedImages.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:49 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Source.cs
> +namespace pl.coderion.model
Done

2023-10-26 22:54 UTC, MadInventorQDB commented on openfoodfacts-csharp/Services/OpenFoodFactsWrapperImpl.cs
> +namespace pl.coderion.service.impl
Done

2023-10-26 22:55 UTC, MadInventorQDB commented on openfoodfacts-csharp/Services/Interfaces/IOpenFoodFactsWrapper.cs
> +namespace pl.coderion.service
Coment

2023-10-26 22:55 UTC, MadInventorQDB commented on openfoodfacts-csharp/Services/Interfaces/IOpenFoodFactsWrapper.cs
> +namespace pl.coderion.service
Done

2023-10-26 23:24 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
This is a complicated issue, but I will move to netstandard2.1 and still keep nullable fields.
That will also require moving everything to Newtonsoft for JSON support, but .......done.

2023-10-27 03:19 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Product.cs
Both Done.

2023-10-27 03:25 UTC, aberteau requested changes

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Clients/OpenFoodFactsApiLowLevelClient.cs
> +namespace OpenFoodFactsCSharp.client
- The namespace component must match the directory name
If the directory is called "Clients", the namespace component should be "Clients" and not "client"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.client` -> `OpenFoodFactsCSharp.Clients`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Images.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Ingredient.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/LanguagesCodes.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/NutrientLevels.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Nutriments.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Product.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/ProductResponse.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImage.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImageItem.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/SelectedImages.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Source.cs
> +namespace OpenFoodFactsCSharp.model
- The namespace component must match the directory name
If the directory is called "Models", the namespace component should be "Models" and not "model"

- Namespace must use PascalCasing

`OpenFoodFactsCSharp.model` -> `OpenFoodFactsCSharp.Models`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Services/Interfaces/IOpenFoodFactsWrapper.cs
> +namespace OpenFoodFactsCSharp.services.interfaces
- The namespace component must match the directory name.
- Namespace must use PascalCasing.

`OpenFoodFactsCSharp.services.interfaces` -> `OpenFoodFactsCSharp.Services.Interfaces`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Services/OpenFoodFactsWrapperImpl.cs
> +namespace OpenFoodFactsCSharp.services
- The namespace component must match the directory name
- Namespace must use PascalCasing

`OpenFoodFactsCSharp.services` -> `OpenFoodFactsCSharp.Services`

(See [Framework design guidelines/Names of Namespaces](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/Models/Product.cs
All properties are Camel Case. Can you please use Pascal Case ?

> PascalCasing is always used for property names.

(See [Framework design guidelines/Names of Type Members/Names of Properties](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties))

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
### About Nullable Properties
There is no pb with netstandard2.0 or netstandard2.1.

- Nullable value types (`float`, `bool`, ...)  : they are handled without the need to specify `<Nullable>enable</Nullable>` in csproj (`float` -> `float?`, `bool` -> `bool?`, ...)

- Nullable reference types (`string`, class, ...)
Since all your properties having reference types are nullable,  there is no need to distinguish `T` and `T?`.
In netstandard, all reference types are nullable. (This is the default behavior)

For example, I only saw `String?` in your code, no `String`.  So there is no need to distinguish `String` and `String?`.
We could question ourselves if we had non-nullable reference types but this is not the case here.

In netstandard (and more generally in versions not supporting `<Nullable>enable</Nullable>`) `String` is already Nullable and therefore equivalent to `String?`.

⚠️ Furthermore, prior to .NET 6, projects file (csproj) do not include the `Nullable` element.

For more information :
- [Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
- [Nullable value types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types)
- [Tutorial: Express your design intent more clearly with nullable and non-nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types)

### About JSON Serialization
I understand. 👍 But it's not really a problem.
_System.Text.Json_ is generally faster than _Newtonsoft.Json_, especially for large data sets but _Newtonsoft.Json_ has a simpler and more flexible API compared to _System.Text.Json_. It provides many options for controlling serialization and deserialization behavior, and has a more intuitive error handling mechanism.
_Newtonsoft.Json_ has been widely used in .NET applications for many years and is compatible with a wide range of .NET versions and platforms.

I don't think performance is a major concern, _Newtonsoft.Json_ is more suitable in this case (more flexible API, need to support older versions of .NET)

Using _Newtonsoft.Json_ instead of _System.Text.Json_ is an acceptable compromise. 😉

### About TargetFramework
If we target `netstandard2.1`, it seems more interesting to target `netstandard2.0`. This does not require any additional modification compared to netstandard2.1 and this will be compatible with a wide range of .NET versions and platforms.

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>netstandard2.1</TargetFramework>
it seems more interesting to target _netstandard2.0_. This does not require any additional modification compared to _netstandard2.1_ and this will be compatible with a wide range of .NET versions and platforms. 😉

(See discussion on the previous review https://github.com/openfoodfacts/openfoodfacts-csharp/pull/1#discussion_r1372798381)

2023-10-27 03:25 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
Prior to .NET 6, projects file (csproj) do not include the `Nullable` element.

(See discussion on the previous review https://github.com/openfoodfacts/openfoodfacts-csharp/pull/1#discussion_r1372798381)

2023-10-27 03:34 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Targeting 2.0 gives this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8630	Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.	OpenFoodFacts-CSharp	C:\Users\johna\source\repos\openfoodfacts-csharp\OpenFoodFacts-CSharp\CSC	1	Active

?

2023-10-27 03:42 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
> Targeting 2.0 gives this error:
> 
> Severity Code Description Project File Line Suppression State Error CS8630 Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater. OpenFoodFacts-CSharp C:\Users\johna\source\repos\openfoodfacts-csharp\OpenFoodFacts-CSharp\CSC 1 Active
> 
> ?
> 
> Nullable fields could be removed, but is that desirable?

I explained everything in the previous comment 😉
See https://github.com/openfoodfacts/openfoodfacts-csharp/pull/1#discussion_r1374016931

2023-10-27 04:05 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Since I don't understand what you want here and you do, can you pull the branch make the change and push it back up?

2023-10-27 04:26 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Done

See this commit https://github.com/openfoodfacts/openfoodfacts-csharp/commit/58bacc058bf012ca0d12bca31f56d0e0a4c29338

2023-10-27 05:10 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
@MadInventorQDB It will be really complicated to work together if you make changes then cancelled by rewriting history with forced push...😅

⚠️If you work on a branch with somebody else, it's better not to rewrite history.
If you cannot do otherwise, it's better to warn.

I had improvements to push.
Since you pushed a commit "Normalized line endings. An more namespace matching to file structure" (https://github.com/openfoodfacts/openfoodfacts-csharp/commit/bf7c8783525f4da2f733f7bfe760c49693da502f). I had to rebase my modifications and resolve conflicts. When I wanted to commit my changes, git told me that I had to resolve conflicts again (you had deleted your commit by rewriting the history).

👉 If you ask someone to push on your working branch, please don't rewrite history with `push --force` 🙏

2023-10-27 08:40 UTC, hangy commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
If you can use `Nullable` or not doesn't necessarily depend on the .NET runtime version, but the C# language version/compiler. I have successfully used it with older frameworks, as long as the language and compiler version are correct, ie.
```xml
    <LangVersion>11.0</LangVersion>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
```

2023-10-27 09:05 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
Thank you @hangy for this addition but due to the author's level in C#/Net, it did not seem necessary to go into detail. 😉I have provided all the necessary links for those who want to know more about this subject.

We don't know the level of the author, his environnement (Visual Studio, Visual Studio Code, Rider, ...), ...
I'm here to review a pull request and not to teach a course on C#/.Net Platform.

My goal is to ensure that modifications are **quickly** integrated by ensuring that the code respects certain rules to facilitate collaboration.

Regarding PR, the quickest and most understandable solution was to modify the csproj.
`<TargetFramework>netstandard2.0.</TargetFramework>`

Given the current code (all properties are Nullable), I don't see any benefit in making things more complex 🤷‍♂️

2023-10-27 13:50 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +        <TargetFramework>net6.0</TargetFramework>
I did a bad push, for some reason the rename of the namespace added the nullable  strings back. and didn't know you were going to make another change. I'll go ahead and make namespace changes now,

2023-10-27 14:00 UTC, MadInventorQDB commented on openfoodfacts-csharp/Clients/OpenFoodFactsApiLowLevelClient.cs
> +namespace OpenFoodFactsCSharp.client
Done

2023-10-27 14:00 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Images.cs
> +namespace OpenFoodFactsCSharp.model
Done

2023-10-27 14:00 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Ingredient.cs
> +namespace OpenFoodFactsCSharp.model
Done

2023-10-27 14:01 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/LanguagesCodes.cs
> +namespace OpenFoodFactsCSharp.model
Done

2023-10-27 14:01 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/NutrientLevels.cs
> +namespace OpenFoodFactsCSharp.model
Done

2023-10-27 14:01 UTC, MadInventorQDB commented on openfoodfacts-csharp/Services/OpenFoodFactsWrapperImpl.cs
> +namespace OpenFoodFactsCSharp.services
Done

2023-10-27 14:02 UTC, MadInventorQDB commented on openfoodfacts-csharp/Models/Product.cs
Done.

2023-10-27 14:10 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
Nullable reference types can be particularly useful in JSON deserialization for several reasons:

Express Intent Clearly: By marking a property as string? in a DTO or a model class, you're clearly indicating that this property might not be present or might have a null value in the JSON payload. This can be particularly useful for APIs where certain fields are optional.

Safety: When nullable reference types are enabled, the compiler will warn you if you try to access a property that can be null without checking its nullability first. This can prevent potential NullReferenceException issues in your code.

Validation: If a property is marked as non-nullable (e.g., string instead of string?), but the JSON payload contains a null or the property is missing, certain JSON deserializers can be configured to throw an exception, which can be useful for input validation.

Improved Code Quality: By being explicit about nullability in your models, developers are forced to think about and handle the absence of data, leading to more robust code.

Integration with Modern Tools: Modern JSON libraries, like System.Text.Json and Newtonsoft.Json, can be configured to work seamlessly with nullable reference types, ensuring that the deserialization behavior aligns with the nullability annotations in your models.

In JSON deserialization where data might be optional or missing, nullable reference types provide a type-safe way to express and handle the absence of data.

2023-10-27 15:44 UTC, aberteau commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
Ok, I didn't say it was useless. 😉
But in the currently proposed code :
- no property is defined as not-nullable
- There is no test explaining this intention and verifying this specification

I was talking about the code you commited to work with the Open Food Facts API, not the code in general.

- Can you please show some parts of your code where not-nullable/nullable is usefull  ?
- Do you have JSON Schema or any other documentation about Product Data Structure specifying which fields are nullable or not ?

I don't think that we have this information today.
I just ask you if, in the context of OpenFoodFacts, it's really useful to have a system allowing to be strict on types but systematically mark all properties as Nullable.

2023-10-27 16:54 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
I was going for an initial PR that works. I appreciate all the feed back. I was being sloppy with my code because it wasn't going to be a release yet. I didn't realize how seriously you were taking this. If you are going to be putting work into this, I'll be structured and precise. Thanks.

2023-10-27 16:56 UTC, MadInventorQDB commented on openfoodfacts-csharp/OpenFoodFacts-CSharp.csproj
> +		<Nullable>enable</Nullable>
I didn't write any tests for the JSON models, other than Product, which was really more about making sure the API worked.

2023-10-31 14:26 UTC, merged